# Generated by Django 4.2.1 on 2023-06-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='img',
            field=models.ImageField(default='aaa', upload_to='pics'),
            preserve_default=False,
        ),
    ]
